dist: trusty
sudo: required
language: php
php:
  - 7.0
  - 7.1

install:
  - composer install --dev --no-interaction

script:
  - mkdir build
  - cd tests
  - phpunit --coverage-clover ../build/clover.xml --configuration phpunit.xml
  - cd ..


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
